# https://ls-lint.org/1.x/configuration/the-rules.html
ls:
  .dir: kebab-case | snake_case | regex:.[a-z0-9]+ | regex:[[a-z0-9]+] # TODO clean this up
  .go: snake_case
  .deepcopy.go: snake_case
  .proto: snake_case
  .bazel: SCREAMING_SNAKE_CASE
  .html: kebab-case
  .css: kebab-case
  .png: kebab-case
  .jpg: kebab-case
  .json: kebab-case | regex:.[a-z0-9]+ | regex:tsconfig[a-z0-9.]*
  .js: kebab-case
  .config.js: kebab-case
  .ts: kebab-case | regex:_[a-z0-9]+ | regex:[a-z0-9]+.config
  .tsx: kebab-case | regex:_[a-z0-9]+ | regex:[[a-z0-9]+]
  .test.ts: kebab-case
  .test.tsx: kebab-case
  .d.ts: kebab-case

ignore:
  - .git
  - .idea
  - .github
  - docs
  - debug
  - node_modules
  - packages/cli/lib
  - packages/cli/node_modules
  - packages/cli/templates
  - packages/sdk/src/eth/abis
  - packages/sdk/src/eth/builtin/internal
  - packages/sdk/docs
  - packages/sdk/lib
  - packages/sdk/node_modules
  - examples
  - packages/sdk/src/eth/tests
  - packages/protos/lib
  - packages/protos/node_modules
  - packages/runtime/lib
  - packages/runtime/node_modules
  - packages/sdk/src/solana/tests
  - packages/sdk/src/fuel/tests
  - packages/sdk/src/stark/tests
  - packages/sdk/src/tests
  - packages/action/node_modules
  - packages/action/lib
  - .claude