export type InternalTokenInfo = {
  chainId: number
  tokenAddress: `0x${string}` | null
  faAddress: `0x${string}` | null
  name: string
  symbol: string
  decimals: number
  bridge: 'LayerZero' | 'Wormhole' | 'Celer' | 'Echo' | null
  panoraSymbol: string
  logoUrl: string | null
  websiteUrl: string | null
  category: 'Native' | 'Bridged' | 'Meme'
  isInPanoraTokenList: boolean
  isBanned: boolean
  panoraOrderIndex: number | null
  coinGeckoId: string | null
  coinMarketCapId: number | null
}

export const DEFAULT_TOKEN_LIST: InternalTokenInfo[] = [
  {
    chainId: 1,
    tokenAddress: '0x1::aptos_coin::AptosCoin',
    faAddress: '0xa',
    name: 'Aptos Coin',
    symbol: 'APT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APT.svg',
    websiteUrl: 'https://aptosfoundation.org',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 1,
    coinGeckoId: 'aptos',
    coinMarketCapId: 21794
  },
  {
    chainId: 1,
    tokenAddress: null,
    faAddress: '0x357b0b74bc833e95a115ad22604854d6b0fca151cecd94111770e5d6ffc9dc2b',
    name: 'Tether USD',
    symbol: 'USDt',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'USDt',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDT.svg',
    websiteUrl: 'https://tether.to',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 2,
    coinGeckoId: 'tether',
    coinMarketCapId: 825
  },
  {
    chainId: 1,
    tokenAddress: '0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC',
    faAddress: '0x2b3be0a97a73c87ff62cbdd36837a9fb5bbd1d7f06a73b7ed62ec15c5326c1b8',
    name: 'USD Coin',
    symbol: 'USDC',
    decimals: 6,
    bridge: 'LayerZero',
    panoraSymbol: 'lzUSDC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDC.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 10,
    coinGeckoId: 'usd-coin',
    coinMarketCapId: 3408
  },
  {
    chainId: 1,
    tokenAddress: '0x5ae6789dd2fec1a9ec9cccfb3acaf12e93d432f0a3a42c92fe1a9d490b7bbc06::mkl_token::MKL',
    faAddress: '0x878370592f9129e14b76558689a4b570ad22678111df775befbfcbc9fb3d90ab',
    name: 'Merkle',
    symbol: 'MKL',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'MKL',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MKL.png',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 15,
    coinGeckoId: 'merkle-trade',
    coinMarketCapId: 32997
  },
  {
    chainId: 1,
    tokenAddress: '0x53a30a6e5936c0a4c5140daed34de39d17ca7fcae08f947c02e979cef98a3719::coin::LSD',
    faAddress: '0x2370cc1d995f3aadd337c1c6c63834ad8d2bd0cdc70bc8dff81de463e18b159',
    name: 'Liquidswap',
    symbol: 'LSD',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'LSD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/LSD.png',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 20,
    coinGeckoId: 'pontem-liquidswap',
    coinMarketCapId: 22262
  },
  {
    chainId: 1,
    tokenAddress: '0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDT',
    faAddress: null,
    name: 'Tether USD',
    symbol: 'USDT',
    decimals: 6,
    bridge: 'LayerZero',
    panoraSymbol: 'lzUSDT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDT_BRIDGED.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 25,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::WETH',
    faAddress: null,
    name: 'Wrapped Ether',
    symbol: 'WETH',
    decimals: 6,
    bridge: 'LayerZero',
    panoraSymbol: 'lzWETH',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/WETH.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 30,
    coinGeckoId: 'ethereum',
    coinMarketCapId: 1027
  },
  {
    chainId: 1,
    tokenAddress: '0x4e1854f6d332c9525e258fb6e66f84b6af8aba687bbcb832a24768c4e175feec::abtc::ABTC',
    faAddress: null,
    name: 'aBTC',
    symbol: 'aBTC',
    decimals: 10,
    bridge: 'Echo',
    panoraSymbol: 'aBTC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/aBTC.svg',
    websiteUrl: 'https://www.echo-protocol.xyz',
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 33,
    coinGeckoId: 'abtc',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0x543c5660aa4d496687e2068c11765f04607c4f4b639a83233a9333604fb8ce59::stakestone_ether::StakeStoneEther',
    faAddress: null,
    name: 'StakeStone Ether',
    symbol: 'STONE',
    decimals: 8,
    bridge: 'LayerZero',
    panoraSymbol: 'lzSTONE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/STONE.svg',
    websiteUrl: 'https://stakestone.io',
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 35,
    coinGeckoId: 'stakestone-ether',
    coinMarketCapId: 32194
  },
  {
    chainId: 1,
    tokenAddress:
      '0x5dee1d4b13fae338a1e1780f9ad2709a010e824388efd169171a26e3ea9029bb::stakestone_bitcoin::StakeStoneBitcoin',
    faAddress: null,
    name: 'StakeStone Bitcoin',
    symbol: 'SBTC',
    decimals: 8,
    bridge: 'LayerZero',
    panoraSymbol: 'lzSBTC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SBTC.svg',
    websiteUrl: 'https://stakestone.io',
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 37,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x7fd500c11216f0fe3095d0c4b8aa4d64a4e2e04f83758462f2b127255643615::thl_coin::THL',
    faAddress: '0x377adc4848552eb2ea17259be928001923efe12271fef1667e2b784f04a7cf3a',
    name: 'Thala Token',
    symbol: 'THL',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'THL',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/THL.svg',
    websiteUrl: 'https://www.thala.fi',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 40,
    coinGeckoId: 'thala',
    coinMarketCapId: 24268
  },
  {
    chainId: 1,
    tokenAddress: null,
    faAddress: '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12',
    name: 'Cellana',
    symbol: 'CELL',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'CELL',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CELL.png',
    websiteUrl: 'https://cellana.finance',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 45,
    coinGeckoId: 'cellena-finance',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x42d77150661adcc068603bde2453bea1e22fa7ca08878ec88b7e077709c01171::oft::WUSDMOFT',
    faAddress: null,
    name: 'Wrap USDM',
    symbol: 'WUSDM',
    decimals: 8,
    bridge: 'LayerZero',
    panoraSymbol: 'lzWUSDM',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/WUSDM.png',
    websiteUrl: 'https://mountainprotocol.com',
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 48,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xcfea864b32833f157f042618bd845145256b1bf4c0da34a7013b76e42daa53cc::usdy::USDY',
    faAddress: null,
    name: 'Ondo US Dollar Yield',
    symbol: 'USDY',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'USDY',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDY.svg',
    websiteUrl: 'https://ondo.finance',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 50,
    coinGeckoId: 'ondo-us-dollar-yield',
    coinMarketCapId: 29256
  },
  {
    chainId: 1,
    tokenAddress: '0x268d4a7a2ad93274edf6116f9f20ad8455223a7ab5fc73154f687e7dbc3e3ec6::LOON::LOON',
    faAddress: null,
    name: 'The Loonies',
    symbol: 'LOON',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'LOON',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/LOON.jpg',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 55,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xe4ccb6d39136469f376242c31b34d10515c8eaaa38092f804db8e08a8f53c5b2::assets_v1::EchoCoin002',
    faAddress: null,
    name: 'Gui Inu',
    symbol: 'GUI',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'GUI',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/GUI.png',
    websiteUrl: 'https://www.guiinu.com',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 60,
    coinGeckoId: 'gui-inu',
    coinMarketCapId: 28851
  },
  {
    chainId: 1,
    tokenAddress: '0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::amapt_token::AmnisApt',
    faAddress: null,
    name: 'Amnis Aptos Coin',
    symbol: 'amAPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'amAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/amAPT.png',
    websiteUrl: 'https://amnis.finance',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 65,
    coinGeckoId: 'amnis-aptos',
    coinMarketCapId: 29034
  },
  {
    chainId: 1,
    tokenAddress: '0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT',
    faAddress: '0xa0d9d647c5737a5aed08d2cfeb39c31cf901d44bc4aa024eaa7e5e68b804e011',
    name: 'Thala APT',
    symbol: 'thAPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'thAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/THAPT.svg',
    websiteUrl: 'https://thala.fi',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 70,
    coinGeckoId: 'thala-apt',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::stapt_token::StakedApt',
    faAddress: '0xb614bfdf9edc39b330bbf9c3c5bcd0473eee2f6d4e21748629cc367869ece627',
    name: 'Staked Aptos Coin',
    symbol: 'stAPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'stAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/stAptAmnis.png',
    websiteUrl: 'https://stake.amnis.finance',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 75,
    coinGeckoId: 'amnis-staked-aptos-coin',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT',
    faAddress: null,
    name: 'Staked Thala APT',
    symbol: 'sthAPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'sthAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/STHAPT.svg',
    websiteUrl: 'https://thala.fi',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 80,
    coinGeckoId: 'staked-thala-apt',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x6f986d146e4a90b828d8c12c14b6f4e003fdff11a8eecceceb63744363eaac01::mod_coin::MOD',
    faAddress: '0x94ed76d3d66cb0b6e7a3ab81acf830e3a50b8ae3cfb9edc0abea635a11185ff4',
    name: 'Move Dollar',
    symbol: 'MOD',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MOD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MOD.svg',
    websiteUrl: 'https://thala.fi',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 85,
    coinGeckoId: 'move-dollar',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea::coin::T',
    faAddress: '0x54fc0d5fa5ad975ede1bf8b1c892ae018745a1afd4a4da9b70bb6e5448509fc0',
    name: 'USD Coin',
    symbol: 'USDC',
    decimals: 6,
    bridge: 'Wormhole',
    panoraSymbol: 'whUSDC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDC.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 90,
    coinGeckoId: 'usd-coin',
    coinMarketCapId: 3408
  },
  {
    chainId: 1,
    tokenAddress: '0x73eb84966be67e4697fc5ae75173ca6c35089e802650f75422ab49a8729704ec::coin::DooDoo',
    faAddress: '0xb27b0c6b60772f0fc804ec1cd3339f552badf9bd1e125a7dd700d8eb11248ef1',
    name: 'DooDoo',
    symbol: 'DooDoo',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'DooDoo',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DOODOO.png',
    websiteUrl: 'https://doodoo.io',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 95,
    coinGeckoId: 'doodoo',
    coinMarketCapId: 28881
  },
  {
    chainId: 1,
    tokenAddress: '0x4fbed3f8a3fd8a11081c8b6392152a8b0cb14d70d0414586f0c9b858fcd2d6a7::UPTOS::UPTOS',
    faAddress: null,
    name: 'UPTOS',
    symbol: 'UPTOS',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'UPTOS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/UPTOS.svg',
    websiteUrl: 'https://uptos.xyz',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 100,
    coinGeckoId: 'uptos',
    coinMarketCapId: 30366
  },
  {
    chainId: 1,
    tokenAddress: '0x63be1898a424616367e19bbd881f456a78470e123e2770b5b5dcdceb61279c54::movegpt_token::MovegptCoin',
    faAddress: null,
    name: 'MOVEGPT',
    symbol: 'MGPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MGPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MGPT.jpg',
    websiteUrl: 'https://movegpt.io/',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 105,
    coinGeckoId: 'movegpt',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xe88ae9670071da40a9a6b1d97aab8f6f1898fdc3b8f1c1038b492dfad738448b::coin::Donk',
    faAddress: null,
    name: 'Donk',
    symbol: 'DONK',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'DONK',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DONK.png',
    websiteUrl: 'https://donkmove.com/',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 110,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x5e975e7f36f2658d4cf146142899c659464a3e0d90f0f4d5f8b2447173c06ef6::EDOG::EDOG',
    faAddress: null,
    name: 'EDOG',
    symbol: 'EDOG',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'EDOG',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/EDOG.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 112,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x2d4de7378c573dadc2e589892d709ee24f3c26f23b57804f384f4803da2e6f0a::ZIPO::ZIPO',
    faAddress: null,
    name: 'ZIPPO THE OG MASCOT',
    symbol: 'ZIPO',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'ZIPO',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ZIPO.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 114,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xdcfa079344261bfde45e7f6281df091743b8d3098bf9e26e1c0212fc5b070621::zaaptos_token::ZaaptosCoin',
    faAddress: null,
    name: 'Zaaptos Coin',
    symbol: 'ZAAP',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ZAAP',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ZAAP.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 115,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6::oft::CakeOFT',
    faAddress: null,
    name: 'PancakeSwap Token',
    symbol: 'CAKE',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'CAKE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/Pancake.png',
    websiteUrl: 'https://pancakeswap.finance',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 120,
    coinGeckoId: 'pancakeswap-token',
    coinMarketCapId: 7186
  },
  {
    chainId: 1,
    tokenAddress: null,
    faAddress: '0xaef6a8c3182e076db72d64324617114cacf9a52f28325edc10b483f7f05da0e7',
    name: 'TruAPT coin',
    symbol: 'TruAPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'TruAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/TruAPT.png',
    websiteUrl: 'https://www.trufin.io',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 125,
    coinGeckoId: 'trufin-staked-apt',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x27fafcc4e39daac97556af8a803dbb52bcb03f0821898dc845ac54225b9793eb::move_coin::MoveCoin',
    faAddress: null,
    name: 'BlueMove',
    symbol: 'MOVE',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MOVE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MOVE.svg',
    websiteUrl: 'https://bluemove.net',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 130,
    coinGeckoId: 'bluemove',
    coinMarketCapId: 23359
  },
  {
    chainId: 1,
    tokenAddress: '0xe234f0e7c05165cc48f5407c3eb542709a8284fb6b9d66068413a2e13ef423bd::MOVEPUMP::MOVEPUMP',
    faAddress: null,
    name: 'MovePump',
    symbol: 'MOVEPUMP',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'MOVEPUMP',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MOVEPUMP.webp',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 133,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xada35ada7e43e2ee1c39633ffccec38b76ce702b4efc2e60b50f63fbe4f710d8::apetos_token::ApetosCoin',
    faAddress: '0xfad230e7d9df2baf83a68b6f50217ed3c06da593e766970a885965b43b894a04',
    name: 'APETOS',
    symbol: 'APE',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APE.png',
    websiteUrl: 'https://apetos.xyz/',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 135,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xd6a49762f6e4f7401ee79be6f5d4111e70db1408966ba1aa204e6e10c9d437ca::bubbles::BubblesCoin',
    faAddress: null,
    name: 'BUBBLES',
    symbol: 'BUBBLES',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'BUBBLES',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BUBBLES.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 140,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x198e4a77b72cbcac7465e774e99d2ba552053ca57b0759ea3c008433742b4e4f::PEPE::Pepe',
    faAddress: null,
    name: 'Pepe',
    symbol: 'PEPE',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'PEPE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/PEPE.png',
    websiteUrl: 'https://pepe.as',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 145,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xc26a8eda1c3ab69a157815183ddda88c89d6758ee491dd1647a70af2907ce074::coin::Chewy',
    faAddress: null,
    name: 'Chewy',
    symbol: 'CHEWY',
    decimals: 0,
    bridge: null,
    panoraSymbol: 'CHEWY',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CHEWY.png',
    websiteUrl: 'https://chewytoken.com',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 150,
    coinGeckoId: null,
    coinMarketCapId: 30840
  },
  {
    chainId: 1,
    tokenAddress:
      '0x4c71c33b9ec2f263a7f25779bd9a2531165d4da9a963e042a20f288688094a66::APTO_THE_MASCOT::APTO_THE_MASCOT',
    faAddress: null,
    name: 'Apto The Mascot',
    symbol: 'APTO',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APTO',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APTO.png',
    websiteUrl: 'https://aptothemascot.com/',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 155,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xf891d2e004973430cc2bbbee69f3d0f4adb9c7ae03137b4579f7bb9979283ee6::APTOS_FOMO::APTOS_FOMO',
    faAddress: null,
    name: 'APTOS FOMO',
    symbol: 'FOMO',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'FOMO',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/FOMO.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 160,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x7b7bab2131de3e4f318b4abaa952f7c817b2c3df16c951caca809ac9ca9b650e::APARTMENT::APARTMENT',
    faAddress: null,
    name: 'APARTMENT',
    symbol: 'APARTMENT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APARTMENT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APARTMENT.png',
    websiteUrl: 'https://aptosapartments.rent',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 165,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xdf3d5eb83df80dfde8ceb1edaa24d8dbc46da6a89ae134a858338e1b86a29e38::coin::Returd',
    faAddress: null,
    name: 'Returd',
    symbol: 'RETuRD',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'RETuRD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/RETURD.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 170,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: null,
    faAddress: '0xe9c6ae7a056ba49901fcc19ab3fcff0938f882cfd7f2cc5a72eea362d29f5b8f',
    name: 'BAPTMAN',
    symbol: 'BAPTMAN',
    decimals: 9,
    bridge: null,
    panoraSymbol: 'BAPTMAN',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BAPTMAN.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 173,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x13341e81b2c5960623f31cfee0b1ef674cbf23ca302852159b542adc6afe0f37::TEH_DORK_KNITE::TEH_DORK_KNITE',
    faAddress: null,
    name: 'Teh Dork Knite',
    symbol: 'BAPTMAN',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'BAPTMAN',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BAPTMAN.jpg',
    websiteUrl: 'https://baptmantoken.com',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 175,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xd2c9cfe8dd64ebdf9b39e1525997cef33bd178161c59410097d3f3e0704a5df3::ROO::ROO',
    faAddress: null,
    name: 'ROO',
    symbol: 'ROO',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ROO',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ROO.jpg',
    websiteUrl: 'https://aptosroo.io',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 180,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::WBTC',
    faAddress: null,
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    decimals: 6,
    bridge: 'LayerZero',
    panoraSymbol: 'lzWBTC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BTC.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 185,
    coinGeckoId: 'bitcoin',
    coinMarketCapId: 1
  },
  {
    chainId: 1,
    tokenAddress: '0xa2eda21a58856fda86451436513b867c97eecb4ba099da5775520e0f7492e852::coin::T',
    faAddress: null,
    name: 'Tether USD',
    symbol: 'USDT',
    decimals: 6,
    bridge: 'Wormhole',
    panoraSymbol: 'whUSDT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDT_BRIDGED.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 190,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xae478ff7d83ed072dbc5e264250e67ef58f57c99d89b447efd8a0a2e8b2be76e::coin::T',
    faAddress: null,
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whWBTC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BTC.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 195,
    coinGeckoId: 'bitcoin',
    coinMarketCapId: 1
  },
  {
    chainId: 1,
    tokenAddress: '0xcc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abb::coin::T',
    faAddress: null,
    name: 'Wrapped Ether',
    symbol: 'WETH',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whWETH',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/WETH.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 200,
    coinGeckoId: 'ethereum',
    coinMarketCapId: 1027
  },
  {
    chainId: 1,
    tokenAddress: '0xbe3c4b493632b4d776d56e19d91dcfb34f591f759f6b57f8632d455360da503c::dumdum_coin::DumdumCoin',
    faAddress: null,
    name: 'Dumdum',
    symbol: 'DUMDUM',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'DUMDUM',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DUMDUM.png',
    websiteUrl: 'https://dumdum.cc/',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 205,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x665d06fcd9c94430099f82973f2a5e5f13142e42fa172e72ce14f51a64bd8ad9::coin_mbx::MBX',
    faAddress: null,
    name: 'MARBLEX',
    symbol: 'MBX',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MBX',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MBX.png',
    websiteUrl: 'https://marblex.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 210,
    coinGeckoId: 'marblex',
    coinMarketCapId: 18895
  },
  {
    chainId: 1,
    tokenAddress: '0x389dbbc6884a1d5b1ab4e1df2913a8c1b01251e50aed377554372b2842c5e3ef::chad_coin::ChadCoin',
    faAddress: null,
    name: 'CHAD',
    symbol: 'CHAD',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'CHAD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CHAD.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 215,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x1fc2f33ab6b624e3e632ba861b755fd8e61d2c2e6cf8292e415880b4c198224d::apt20::APTS',
    faAddress: null,
    name: 'APTS',
    symbol: 'APTS',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APTS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APTS.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 220,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x4ed27736e724e403f9b4645ffef0ae86fd149503f45b37c428ffabd7e46e5b05::core::RenegadeCoin',
    faAddress: null,
    name: 'RENA',
    symbol: 'RENA',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'RENA',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/RENA.png',
    websiteUrl: 'https://www.renegades.build',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 225,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x7de3fea83cd5ca0e1def27c3f3803af619882db51f34abf30dd04ad12ee6af31::tapos::Heart',
    faAddress: null,
    name: 'Heart',
    symbol: 'HEART',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'HEART',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/HEART.png',
    websiteUrl: 'https://tapos.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 230,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x84edd115c901709ef28f3cb66a82264ba91bfd24789500b6fd34ab9e8888e272::coin::DLC',
    faAddress: null,
    name: 'Doglaika Coin',
    symbol: 'DLC',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'DLC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DLC.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 235,
    coinGeckoId: 'doglaikacoin',
    coinMarketCapId: 23200
  },
  {
    chainId: 1,
    tokenAddress: '0x4d981c48d254c4cea6110090ad1c2890d5ea35d49cbed28e76c0d3bb90ddf873::crab_coin::CrabCoin',
    faAddress: null,
    name: 'Crab Coin',
    symbol: 'CRAB',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'CRAB',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CRAB.svg',
    websiteUrl: 'https://www.aptosshaker.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 240,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xc82974034820c34f065f948f1bee473d481bf99fde2d23e981043e5038cb36be::WOOF::Woof',
    faAddress: null,
    name: 'Woof',
    symbol: 'Woof',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'Woof',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/WOOF.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 245,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x5c738a5dfa343bee927c39ebe85b0ceb95fdb5ee5b323c95559614f5a77c47cf::Aptoge::Aptoge',
    faAddress: '0xf7833d21f83a19548c81e8fd17d8bde4a6e8cc3fbb1ffb97973e06e261c75dee',
    name: 'Aptoge',
    symbol: 'APTOGE',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'APTOGE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APTOGE.png',
    websiteUrl: 'https://aptoge.com',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 250,
    coinGeckoId: null,
    coinMarketCapId: 22383
  },
  {
    chainId: 1,
    tokenAddress: '0x5c738a5dfa343bee927c39ebe85b0ceb95fdb5ee5b323c95559614f5a77c47cf::AptSwap::AptSwapGovernance',
    faAddress: null,
    name: 'AptSwap Governance Token',
    symbol: 'APTSWAP',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APTSWAP',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/AptSwap.png',
    websiteUrl: 'http://aptswap.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 255,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xe50684a338db732d8fb8a3ac71c4b8633878bd0193bca5de2ebc852a83b35099::propbase_coin::PROPS',
    faAddress: null,
    name: 'Propbase',
    symbol: 'PROPS',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'PROPS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/PROPS.png',
    websiteUrl: 'https://www.propbase.app',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 260,
    coinGeckoId: 'propbase',
    coinMarketCapId: 28385
  },
  {
    chainId: 1,
    tokenAddress: '0x881ac202b1f1e6ad4efcff7a1d0579411533f2502417a19211cfc49751ddb5f4::coin::MOJO',
    faAddress: null,
    name: 'Mojito',
    symbol: 'MOJO',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MOJO',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MOJO.svg',
    websiteUrl: 'https://dex.mojito.markets',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 265,
    coinGeckoId: 'mojito',
    coinMarketCapId: 22399
  },
  {
    chainId: 1,
    tokenAddress:
      '0xd0b4efb4be7c3508d9a26a9b5405cf9f860d0b9e5fe2f498b90e68b8d2cedd3e::aptos_launch_token::AptosLaunchToken',
    faAddress: '0xd1bec63fa44dc3f3f5742c3f3a4afc3baed00505efbe955dfe6e5f9d306c67a5',
    name: 'AptosLaunch Token',
    symbol: 'ALT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ALT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ALT.png',
    websiteUrl: 'https://aptoslaunch.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 270,
    coinGeckoId: 'aptos-launch-token',
    coinMarketCapId: 22065
  },
  {
    chainId: 1,
    tokenAddress: '0x7c0322595a73b3fc53bb166f5783470afeb1ed9f46d1176db62139991505dc61::abel_coin::AbelCoin',
    faAddress: null,
    name: 'Abel Coin',
    symbol: 'ABEL',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ABEL',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ABEL.svg',
    websiteUrl: 'https://abelfinance.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 275,
    coinGeckoId: 'abel-finance',
    coinMarketCapId: 22959
  },
  {
    chainId: 1,
    tokenAddress: '0xd11107bdf0d6d7040c6c0bfbdecb6545191fdf13e8d8d259952f53e1713f61b5::staked_coin::StakedAptos',
    faAddress: null,
    name: 'Ditto Staked Aptos',
    symbol: 'stAPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'dstAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/stAptDitto.png',
    websiteUrl: 'https://www.dittofinance.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 280,
    coinGeckoId: 'ditto-staked-aptos',
    coinMarketCapId: 22290
  },
  {
    chainId: 1,
    tokenAddress:
      '0x84d7aeef42d38a5ffc3ccef853e1b82e4958659d16a7de736a29c55fbbeb0114::staked_aptos_coin::StakedAptosCoin',
    faAddress: null,
    name: 'Tortuga Staked Aptos',
    symbol: 'tAPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'tAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/tAptTortuga.png',
    websiteUrl: 'https://tortuga.finance',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 285,
    coinGeckoId: 'tortuga-staked-aptos',
    coinMarketCapId: 22412
  },
  {
    chainId: 1,
    tokenAddress: '0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdtCoin',
    faAddress: null,
    name: 'Tether USD',
    symbol: 'USDT',
    decimals: 6,
    bridge: 'Celer',
    panoraSymbol: 'ceUSDT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDT_BRIDGED.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 290,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xfbab9fb68bd2103925317b6a540baa20087b1e7a7a4eb90badee04abb6b5a16f::blt::Blt',
    faAddress: null,
    name: 'Blocto Token',
    symbol: 'BLT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'BLT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BLT.png',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 295,
    coinGeckoId: 'blocto-token',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xe9c192ff55cffab3963c695cff6dbf9dad6aff2bb5ac19a6415cad26a81860d9::mee_coin::MeeCoin',
    faAddress: null,
    name: 'Meeiro',
    symbol: 'MEE',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'MEE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MEE.svg',
    websiteUrl: 'https://meeiro.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 300,
    coinGeckoId: null,
    coinMarketCapId: 22705
  },
  {
    chainId: 1,
    tokenAddress: '0x52ab49a4039c3d2b0aa6e0a00aaed75dcff72a3120ba3610f62d1d0b6032345a::war_coin::WarCoin',
    faAddress: null,
    name: 'War Coin',
    symbol: 'WAR',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'WAR',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/WAR.png',
    websiteUrl: 'https://werewolfandwitch.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 305,
    coinGeckoId: 'war-coin',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x16fe2df00ea7dde4a63409201f7f4e536bde7bb7335526a35d05111e68aa322c::AnimeCoin::ANI',
    faAddress: '0x9660042a7c01d776938184278381d24c7009ca385d9a59cf9b22691f97615960',
    name: 'AnimeSwap Coin',
    symbol: 'ANI',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ANI',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ANI.png',
    websiteUrl: 'https://animeswap.org',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 310,
    coinGeckoId: 'animeswap',
    coinMarketCapId: 22650
  },
  {
    chainId: 1,
    tokenAddress: '0xc71d94c49826b7d81d740d5bfb80b001a356198ed7b8005ae24ccedff82b299c::bridge::APTS',
    faAddress: null,
    name: 'APTS Token',
    symbol: 'APTS',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APTS-TOKEN',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APTS.png',
    websiteUrl: 'https://bluemove.net/collection/apts',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 315,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x14b0ef0ec69f346bea3dfa0c5a8c3942fb05c08760059948f9f24c02cd0d4fd8::mover_token::Mover',
    faAddress: null,
    name: 'Mover',
    symbol: 'MOVER',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MOVER',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MOVER.svg',
    websiteUrl: 'https://mov3r.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 320,
    coinGeckoId: 'mover-xyz',
    coinMarketCapId: 23767
  },
  {
    chainId: 1,
    tokenAddress: '0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdcCoin',
    faAddress: null,
    name: 'USD Coin',
    symbol: 'USDC',
    decimals: 6,
    bridge: 'Celer',
    panoraSymbol: 'ceUSDC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDC.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 325,
    coinGeckoId: 'usd-coin',
    coinMarketCapId: 3408
  },
  {
    chainId: 1,
    tokenAddress: '0x1000000fa32d122c18a6a31c009ce5e71674f22d06a581bb0a15575e6addadcc::usda::USDA',
    faAddress: null,
    name: 'Argo USD',
    symbol: 'USDA',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'USDA',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDA.png',
    websiteUrl: 'https://argo.fi',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 330,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDD',
    faAddress: null,
    name: 'Decentralized USD',
    symbol: 'USDD',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'USDD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDD.png',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 335,
    coinGeckoId: 'usdd',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x65957cb717d1ec5e13c003cbad0d20d8f7f95236ea0f8bb8c419e533eda73890::TOAST::TOAST',
    faAddress: null,
    name: 'Aptoast',
    symbol: 'TOAST',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'TOAST',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/TOAST.jpg',
    websiteUrl: 'https://aptoast.com',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 340,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::WbtcCoin',
    faAddress: null,
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    decimals: 8,
    bridge: 'Celer',
    panoraSymbol: 'ceWBTC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BTC.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 345,
    coinGeckoId: 'bitcoin',
    coinMarketCapId: 1
  },
  {
    chainId: 1,
    tokenAddress: '0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::WethCoin',
    faAddress: null,
    name: 'Wrapper Ether',
    symbol: 'WETH',
    decimals: 8,
    bridge: 'Celer',
    panoraSymbol: 'ceWETH',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/WETH.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 350,
    coinGeckoId: 'ethereum',
    coinMarketCapId: 1027
  },
  {
    chainId: 1,
    tokenAddress: '0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::DaiCoin',
    faAddress: null,
    name: 'Dai Stablecoin',
    symbol: 'DAI',
    decimals: 8,
    bridge: 'Celer',
    panoraSymbol: 'ceDAI',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DAI.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 355,
    coinGeckoId: 'dai',
    coinMarketCapId: 4943
  },
  {
    chainId: 1,
    tokenAddress: '0x6312bc0a484bc4e37013befc9949df2d7c8a78e01c6fe14a34018449d136ba86::coin::T',
    faAddress: null,
    name: 'Wrapped BNB',
    symbol: 'WBNB',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whWBNB',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BNB.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 360,
    coinGeckoId: 'binancecoin',
    coinMarketCapId: 1839
  },
  {
    chainId: 1,
    tokenAddress: '0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::BnbCoin',
    faAddress: null,
    name: 'Wrapped BNB',
    symbol: 'WBNB',
    decimals: 8,
    bridge: 'Celer',
    panoraSymbol: 'ceWBNB',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BNB.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 365,
    coinGeckoId: 'binancecoin',
    coinMarketCapId: 1839
  },
  {
    chainId: 1,
    tokenAddress: '0xdd89c0e695df0692205912fb69fc290418bed0dbe6e4573d744a6d5e6bab6c13::coin::T',
    faAddress: null,
    name: 'Solana',
    symbol: 'SOL',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whSOL',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SOL.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 370,
    coinGeckoId: 'solana',
    coinMarketCapId: 5426
  },
  {
    chainId: 1,
    tokenAddress: '0x4def3d3dee27308886f0a3611dd161ce34f977a9a5de4e80b237225923492a2a::coin::T',
    faAddress: '0xb81588af2f7d291e8e57f673ec74d4a38f0654633ad6bbeb1cfd4bb0550ae0df',
    name: 'Gari',
    symbol: 'GARI',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whGARI',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/GARI.svg',
    websiteUrl: 'https://gari.network',
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 375,
    coinGeckoId: 'gari-network',
    coinMarketCapId: 12969
  },
  {
    chainId: 1,
    tokenAddress:
      '0x2778b277644d375721766abfff0df2adca795f6cbae9f02ff1c95ce9adb6ee28::aptos_shiba_coin::AptosShibaCoin',
    faAddress: null,
    name: 'Aptos Shiba',
    symbol: 'APTSHIBA',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'AptosShibaCoin',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APTSHIBA.svg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 380,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x66302f3c648890f70ca3fafc42c919483945f3ba155101bc2e149e38a8b93afc::toss_coin::TossCoin',
    faAddress: null,
    name: 'TOSS',
    symbol: 'TOSS',
    decimals: 9,
    bridge: null,
    panoraSymbol: 'TOSS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/TOSS.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 385,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xe1bfc010d2bdd576036f4c1f3ea7d547f19188f5b78075dd961420d843ee914c::brew_coin::BrewCoin',
    faAddress: null,
    name: 'Brewtos',
    symbol: 'BREW',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'BREW',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BREW.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 390,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x777821c78442e17d82c3d7a371f42de7189e4248e529fe6eee6bca40ddbb::apcoin::ApCoin',
    faAddress: null,
    name: 'APass Coin',
    symbol: 'APC',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APC.svg',
    websiteUrl: 'https://aptpp.com',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 395,
    coinGeckoId: null,
    coinMarketCapId: 23226
  },
  {
    chainId: 1,
    tokenAddress: '0x9a19f4c81f7dc7b8ae6f568d562e6fb056c3894303229c91f73f34c24b0403b0::luffycoin::Luffy',
    faAddress: null,
    name: 'LUFFY',
    symbol: 'LUFFY',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'LUFFY',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/LUFFY.webp',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 400,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xcc78307c77f1c2c0fdfee17269bfca7876a0b35438c3442417480c0d5c370fbc::AptopadCoin::APD',
    faAddress: null,
    name: 'Aptopad Coin',
    symbol: 'APD',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'APD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APD.png',
    websiteUrl: 'https://aptopad.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 405,
    coinGeckoId: 'aptopad',
    coinMarketCapId: 24733
  },
  {
    chainId: 1,
    tokenAddress: '0xd0b4efb4be7c3508d9a26a9b5405cf9f860d0b9e5fe2f498b90e68b8d2cedd3e::legendary_meme::LegendaryMEME',
    faAddress: null,
    name: 'Legendary Meme',
    symbol: 'LME',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'LME',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/LME.svg',
    websiteUrl: 'https://legendaryme.me',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 410,
    coinGeckoId: 'legendary-meme',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x5a1e84cdd217034d764abb91bf20aa0536c5a8c900831a37b393fe3af98c3f55::thepeoplecoin::The_People',
    faAddress: null,
    name: 'The People',
    symbol: 'People',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'People',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/PEOPLE.png',
    websiteUrl: 'https://thepeopleapt.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 415,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0xd0b4efb4be7c3508d9a26a9b5405cf9f860d0b9e5fe2f498b90e68b8d2cedd3e::move_ecosystem_fund::MoveEcosystemFund',
    faAddress: null,
    name: 'Move Ecosystem Fund',
    symbol: 'MOVE',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MOVE-MEF',
    logoUrl: null,
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 420,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x3be1b0966a7f400c1ea57e6ddfe5f060282592a1f4df4d45872a7c8bc46b5ba5::zapdos::Zapdos',
    faAddress: null,
    name: 'Zapdos',
    symbol: 'ZAP',
    decimals: 1,
    bridge: null,
    panoraSymbol: 'ZAP',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ZAP.png',
    websiteUrl: 'https://zapdos.dev',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 425,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xc91d826e29a3183eb3b6f6aa3a722089fdffb8e9642b94c5fcd4c48d035c0080::coin::T',
    faAddress: null,
    name: 'USD Coin (Wormhole Solana)',
    symbol: 'USDCso',
    decimals: 6,
    bridge: 'Wormhole',
    panoraSymbol: 'whUSDCso',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDC.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 430,
    coinGeckoId: 'usd-coin',
    coinMarketCapId: 3408
  },
  {
    chainId: 1,
    tokenAddress: '0x79a6ed7a0607fdad2d18d67d1a0e552d4b09ebce5951f1e5c851732c02437595::coin::T',
    faAddress: null,
    name: 'USD Coin (Wormhole BSC)',
    symbol: 'USDCbs',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whUSDCbs',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDC.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 435,
    coinGeckoId: 'usd-coin',
    coinMarketCapId: 3408
  },
  {
    chainId: 1,
    tokenAddress: '0x39d84c2af3b0c9895b45d4da098049e382c451ba63bec0ce0396ff7af4bb5dff::coin::T',
    faAddress: null,
    name: 'USD Coin (Wormhole Avalanche)',
    symbol: 'USDCav',
    decimals: 6,
    bridge: 'Wormhole',
    panoraSymbol: 'whUSDCav',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDC.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 440,
    coinGeckoId: 'usd-coin',
    coinMarketCapId: 3408
  },
  {
    chainId: 1,
    tokenAddress: '0xc7160b1c2415d19a88add188ec726e62aab0045f0aed798106a2ef2994a9101e::coin::T',
    faAddress: null,
    name: 'USD Coin (Wormhole Polygon)',
    symbol: 'USDCpo',
    decimals: 6,
    bridge: 'Wormhole',
    panoraSymbol: 'whUSDCpo',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDC.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 445,
    coinGeckoId: 'usd-coin',
    coinMarketCapId: 3408
  },
  {
    chainId: 1,
    tokenAddress: '0xd6d6372c8bde72a7ab825c00b9edd35e643fb94a61c55d9d94a9db3010098548::USDC::Coin',
    faAddress: null,
    name: 'USD Coin (Multichain)',
    symbol: 'multiUSDC',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'multiUSDC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDC.svg',
    websiteUrl: 'https://multichain.org',
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 450,
    coinGeckoId: 'usd-coin',
    coinMarketCapId: 3408
  },
  {
    chainId: 1,
    tokenAddress: '0x55987edfab9a57f69bac759674f139ae473b5e09a9283848c1f87faf6fc1e789::shrimp::ShrimpCoin',
    faAddress: null,
    name: 'SHRIMP',
    symbol: 'SHRIMP',
    decimals: 2,
    bridge: null,
    panoraSymbol: 'SHRIMP',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SHRIMP.png',
    websiteUrl: 'https://shrimp.app',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 455,
    coinGeckoId: null,
    coinMarketCapId: 29921
  },
  {
    chainId: 1,
    tokenAddress: '0x4ef6d6d174ae393cec4c8af0b75638082fe45c92e552b4df8bc679e3a0ddcb13::CAPTOS::CAPTOS',
    faAddress: null,
    name: 'Captos',
    symbol: 'CAPTOS',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'CAPTOS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CAPTOS.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 460,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x967adbf2e05fe665ab86a3bf2c4acfa39fbf62097963474ef70a0786dae8cfa2::NRUH::NRUH',
    faAddress: null,
    name: 'nRuH BeRs',
    symbol: 'NRUH',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'NRUH',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/NRUH.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 465,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x2dcbc03740a6fa2efee926b9df329184cce357d0573bdab09930f4d48e61a4c8::STOS::STOS',
    faAddress: null,
    name: 'sherritos',
    symbol: 'STOS',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'STOS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/STOS.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 470,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x6f446fe32a361c5512863d5e610f7d7eaa54d5cee1cea6a2712f2e56da693f1c::MODENG::MODENG',
    faAddress: null,
    name: 'Mo Deng',
    symbol: 'MODENG',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'MODENG',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MODENG.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 475,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x61ed8b048636516b4eaf4c74250fa4f9440d9c3e163d96aeb863fe658a4bdc67::CASH::CASH',
    faAddress: null,
    name: 'CASH',
    symbol: 'CASH',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'CASH',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CASH.png',
    websiteUrl: 'https://app.zion.bet',
    category: 'Meme',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 480,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x33df6ad8f2208d8f575076e59fda6e195ef5c1908f0dae9e461a1aada7c12418::SNZ::SNZ',
    faAddress: null,
    name: 'Tissue',
    symbol: 'SNZ',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'SNZ',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SNZ.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 485,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xa8c3d4ec01aa0bcaa23bac67d0c3e9d5df2d9e8b82a01ad4f8448aebf3d9a961::POK::POK',
    faAddress: null,
    name: 'Purrfectly Okay Coin',
    symbol: 'POK',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'POK',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/POK.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 490,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x24dc0c6bd0a98f31961589e6432a8038833128f7c802ba148172553987c379f::MEOW::MEOW',
    faAddress: null,
    name: 'Meowtos',
    symbol: 'MEOW',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'MEOW',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MEOW.svg',
    websiteUrl: 'https://meowtos.xyz',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 495,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x8e36c188da866c4faccb1ace68a33cca40149d942953a6b6a9976e709396ddb8::BEARD::BEARD',
    faAddress: null,
    name: '$BEARD',
    symbol: 'BEARD',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'BEARD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BEARD.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 500,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xaf1077397a61aebda08ff61dfebd571ccdf7a777618b8d66832b5ab0656852bd::FOG::FOG',
    faAddress: null,
    name: 'FAG DOG COIN',
    symbol: 'FOG',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'FOG',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/FOG.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 505,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x23906ec47702dfcdb8ca35dc6eab5cb5d567b86ac1ef0d32a53b786c14ed0d98::POLES::POLES',
    faAddress: null,
    name: 'CHOADpoles',
    symbol: 'POLES',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'POLES',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/POLES.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 510,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x8f59ac670c9cdaa22503bfede0be49e6759626b18727fbf8d876e18861ff3986::RAPT::RAPT',
    faAddress: null,
    name: 'Raptos',
    symbol: 'RAPT',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'RAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/RAPT.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 515,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xbafd66d813a51ed6b5d2db99b18b61d2fccbc2e46979690fe84198272c59ca5f::zaptos::Zaptos',
    faAddress: null,
    name: 'ZAPTOS',
    symbol: 'ZAPT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ZAPT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ZAPT.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 520,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x2ac1304f147af6f3e3362c64f1c9c95dd84f67a8d6e300185e22c5a6f8f661af::PUPTOS::PUPTOS',
    faAddress: null,
    name: 'PUPTOS',
    symbol: 'PUPTOS',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'PUPTOS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/PUPTOS.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 525,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xf9cd51e1211f467c52d91c96491aae6c7a068e5f23736e2b58f885412346624c::PP1::PP',
    faAddress: null,
    name: 'PP token',
    symbol: 'PP',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'PP',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/PP.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 530,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xbd92f54e3ebf1e80a0efa05f8bbd607fc6dd00ec208c0d743ee6ba3c10f03846::APOP::APOP',
    faAddress: null,
    name: 'Apeople Coin',
    symbol: 'APOP',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'APOP',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/APOP.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 535,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x2eebec013472480cc903cf7f118ccadcf813b4bf5e57aafba250746eff2150d5::BEDOG::BEDOG',
    faAddress: null,
    name: 'Baby Edog',
    symbol: 'BEDOG',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'BEDOG',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BEDOG.svg',
    websiteUrl: 'https://edog.baby',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 540,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x55c833f3c668dd863d3848d306e426a33eac615bb93be03fe3a2f721701fec1::UPDOG::UPDOG',
    faAddress: null,
    name: 'UPDOG',
    symbol: 'UPDOG',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'UPDOG',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/UPDOG.png',
    websiteUrl: 'https://updogapt.xyz',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 545,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x1605f6d99b995e8ddb6200fdccccf97a2497fe1f024a46f6c178a501f0d1b60e::ACAT::ACAT',
    faAddress: null,
    name: 'AptoCat',
    symbol: 'ACAT',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'ACAT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ACAT.png',
    websiteUrl: 'https://www.aptocat.xyz',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 550,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xc95e07a20f94acb04f1188b51bafbbeec93363760c066f4ced3884a48137da8a::GHO::GHO',
    faAddress: null,
    name: 'GHOST',
    symbol: 'GHO',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'GHO',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/GHO.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 555,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x135726730c0e4e71652a6726354f148dec46974d5c152b0042ad58b37ea3c864::FaptOS::FaptOS',
    faAddress: null,
    name: 'FaptOS',
    symbol: 'FaptOS',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'FaptOS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/FAPTOS.png',
    websiteUrl: 'https://faptosaptos.com',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 560,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xce1a44fa48a726258a11a499797bc38befa6bc2ef4019b686c59e0a301b1a1c8::BUBU::BUBU',
    faAddress: null,
    name: 'LABUBUTOS',
    symbol: 'BUBU',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'BUBU',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BUBU.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 565,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xbafe0208ba2a3ea2c66a6868f9361a13f4014490e9b77fb0364c5cf55340ffbe::AMAGA::AMAGA',
    faAddress: null,
    name: 'AptosMAGA',
    symbol: 'AMAGA',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'AMAGA',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/AMAGA.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 570,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x68495e47585861928e07e1fc629501b06822b230508bcf05c4fc19bec9a82405::MOTOS::MOTOS',
    faAddress: null,
    name: 'MOTOS',
    symbol: 'MOTOS',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'MOTOS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MOTOS.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 575,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x10a51c8275d90165aec142e326fcd9dc2e8def57d6271a86ef38a0e5a0a8e142::DWIF::DWI',
    faAddress: null,
    name: 'DOGWIFHAIR',
    symbol: 'DWIF',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'DWIF',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DWIF.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 580,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x744467880fbc1a723d8ba8437cd6de3de942789fe6611fc992de8574596c9b5c::CMT::CMT',
    faAddress: null,
    name: 'Cryptomolot',
    symbol: 'CMT',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'CMT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CMT.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 590,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x2f277e648b3761b65818d92f0a7c151cb38a1d33b1a8b18d4c5748bbcd9fcca5::Netzy::Netzy',
    faAddress: null,
    name: 'The Mole Netzy',
    symbol: 'Netzy',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'Netzy',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/NETZY.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 595,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x541e21bc602730511c0b2de1dbb8e77e5e16031931a955dc988bbed3f600b510::Rice::Rice',
    faAddress: null,
    name: 'Rice Token',
    symbol: 'Rice',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'Rice',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/RICE.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 600,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xc89f2e0a7f61424e0b951936820f0423e3f076948dcdced112b76244ed840a25::burritos_coin::BurritosCoin',
    faAddress: null,
    name: 'BURRITOS',
    symbol: 'BURRITOS',
    decimals: 9,
    bridge: null,
    panoraSymbol: 'BURRITOS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BURRITOS.png',
    websiteUrl: 'https://burritos-aptos.com',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 605,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x8ea59d57259d0312fa21e0cb9099d359462d9e0050c9139960ff9a2313ce1c9d::coin::T',
    faAddress: null,
    name: 'o.xyz',
    symbol: 'O',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'O',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/o-xyz.svg',
    websiteUrl: 'https://www.o.xyz',
    category: 'Native',
    isInPanoraTokenList: true,
    isBanned: false,
    panoraOrderIndex: 610,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: null,
    faAddress: '0x3b5200e090d188c274e06b0d64b3f66638fb996fb0b350499975ff36b1f4595',
    name: 'esMKL',
    symbol: 'esMKL',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'esMKL',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/esMKL.png',
    websiteUrl: 'https://merkle.trade',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 10000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0x5ae6789dd2fec1a9ec9cccfb3acaf12e93d432f0a3a42c92fe1a9d490b7bbc06::house_lp::MKLP<0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC>',
    faAddress: null,
    name: 'Merkle LP',
    symbol: 'MKLP',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'MKLP',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MKLP.png',
    websiteUrl: 'https://merkle.trade',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 10000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x389dbbc6884a1d5b1ab4e1df2913a8c1b01251e50aed377554372b2842c5e3ef::EONcoin::EONCoin',
    faAddress: '0xcab64ed0d956462e9b8ba7c340fdb8b9ab52da1503f37b522288bc0c5bf944de',
    name: 'EON',
    symbol: 'EON',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'EON',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/EON.svg',
    websiteUrl: 'https://eonlabz.com',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::BusdCoin',
    faAddress: null,
    name: 'Binance USD',
    symbol: 'BUSD',
    decimals: 8,
    bridge: 'Celer',
    panoraSymbol: 'ceBUSD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BUSD.png',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'binance-usd',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x25a64579760a4c64be0d692327786a6375ec80740152851490cfd0b53604cf95::coin::ETERN',
    faAddress: null,
    name: 'Eternal Token',
    symbol: 'ETERN',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ETERN',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ETERN.svg',
    websiteUrl: 'https://eternalfinance.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xd916a950d4c1279df4aa0d6f32011842dc5c633a45c11ac5019232c159d115bb::coin::T',
    faAddress: null,
    name: 'wTBT Pool',
    symbol: 'wTBT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'wTBT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/WTBT.svg',
    websiteUrl: 'https://www.tprotocol.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'wtbt',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xccc9620d38c4f3991fa68a03ad98ef3735f18d04717cb75d7a1300dd8a7eed75::coin::T',
    faAddress: null,
    name: 'Binance USD',
    symbol: 'BUSD',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whBUSD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BUSD.png',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'binance-usd',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xced3e98a47279b4d39a75fa8da867e2e8383d5d8ce7e59b2964a9469616a761b::coin::T',
    faAddress: null,
    name: 'Wrapped SUI',
    symbol: 'WSUI',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'WSUI',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SUI.svg',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x33afc05395020c12a31ada7d7d833f31ae1dd892124edec50297c7d608a6e7bd::NEBULA::NEBULA',
    faAddress: null,
    name: 'Nebula',
    symbol: 'NBUL',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'NBUL',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/NBUL.svg',
    websiteUrl: 'https://nebuladao.space',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x9906c12b3b7a12721b9dddf23e6dd5ff5dfc93c5241dada855780758b01fedd3::DOOT_SKELETON::DOOT_SKELETON',
    faAddress: null,
    name: 'DOOT Skeleton',
    symbol: 'DOOT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'DOOT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DOOT.svg',
    websiteUrl: 'https://skeltal.io',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x8235f05ea1901e682bc09b3be93eba0727e94c020ccb0e57074843315c675521::BLADEEWIFHAT::BLADEEWIFHAT',
    faAddress: null,
    name: 'bladeewifhat',
    symbol: 'BLADEE',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'BLADEE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BLADEE.jpg',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x7bdeaba6f037caf06bb5b2d57df9ee03a07e2a9df45b338ef3deb44d16c01d10::spring_coin::Spring_Coin',
    faAddress: null,
    name: 'SPRING',
    symbol: 'SPRING',
    decimals: 9,
    bridge: null,
    panoraSymbol: 'SPRING',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SPRING.webp',
    websiteUrl: 'https://springers.co.in',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'spring',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x27975005fd8b836a905dc7f81c51f89e76091a4d0c4d694265f6eae0c05cb400::proton_a5d::PROTON_E54',
    faAddress: '0x8b91a08070628408c7130b82ce8789e13d978edfccb6db02b79c493ead63a2e8',
    name: 'AlpacaINU Coin',
    symbol: 'ALI',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'ALI',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ALI.svg',
    websiteUrl: 'https://twitter.com/AlpacaINU',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0xd11107bdf0d6d7040c6c0bfbdecb6545191fdf13e8d8d259952f53e1713f61b5::ditto_discount_coin::DittoDiscountCoin',
    faAddress: null,
    name: 'Ditto Discount Token',
    symbol: 'DTO',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'DTO',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DTO.svg',
    websiteUrl: 'https://www.dittofinance.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'ditto-discount-token',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x66398cf97d29fd3825f65b37cb2773268e5438d37e20777e6a98261da0cf1f1e::ddos_coin::DDOS_COIN',
    faAddress: null,
    name: 'DDOS Token',
    symbol: 'DDOS',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'DDOS',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DDOS.svg',
    websiteUrl: 'https://ddosapt.com',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x407a220699982ebb514568d007938d2447d33667e4418372ffec1ddb24491b6c::coin::T',
    faAddress: null,
    name: 'Dai Stablecoin (Wormhole)',
    symbol: 'DAI',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whDAI',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/DAI.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'dai',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xacd014e8bdf395fa8497b6d585b164547a9d45269377bdf67c96c541b7fec9ed::coin::T',
    faAddress: null,
    name: 'Tether USD',
    symbol: 'USDTbs',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whUSDTbs',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/USDT_BRIDGED.svg',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x5b1bbc25524d41b17a95dac402cf2f584f56400bf5cc06b53c36b331b1ec6e8f::coin::T',
    faAddress: null,
    name: 'Wrapped AVAX (Wormhole)',
    symbol: 'WAVAX',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whWAVAX',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/AVAX.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'avalanche-2',
    coinMarketCapId: 5805
  },
  {
    chainId: 1,
    tokenAddress: '0xf6f87fb53c090da2cd681cd30eccec6825685e6f305bfb9efdbbdf31796a83a7::MONKE::MONKE',
    faAddress: null,
    name: 'MONKE',
    symbol: 'MONKE',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'MONKE',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MONKE.png',
    websiteUrl: null,
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x83b619e2d9e6e10d15ed4b714111a4cd9526c1c2ae0eec4b252a619d3e8bdda3::MAU::MAU',
    faAddress: null,
    name: 'MAU',
    symbol: 'MAU',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MAU',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/MAU.png',
    websiteUrl: 'https://mauprotocol.com',
    category: 'Meme',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x9a8d0e2fde92bb5a503ad899b352b630952651cba26e4959d0ed19d79f9b02ee::asset::MoveYourBody',
    faAddress: null,
    name: 'MoveYourBody',
    symbol: 'body',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'body',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BODY.png',
    websiteUrl: 'https://www.moveyourbody.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x1fc2f33ab6b624e3e632ba861b755fd8e61d2c2e6cf8292e415880b4c198224d::apt20::EVA',
    faAddress: null,
    name: 'EVA',
    symbol: 'EVA',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'EVA',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/EVA.png',
    websiteUrl: 'https://apt-20.com',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x7e19e5790911597559ec6b41c5465ab062be22d6ba5729845bf257a2361d7608::CITADELI::CITADELI',
    faAddress: null,
    name: 'Citadeli',
    symbol: 'CTD',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'CTD',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CTD.svg',
    websiteUrl: 'https://citadeli.crypto',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0x8b2df69c9766e18486c37e3cfc53c6ce6e9aa58bbc606a8a0a219f24cf9eafc1::sui_launch_token::SuiLaunchToken',
    faAddress: null,
    name: 'Sui Launch Token',
    symbol: 'SLT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'SLT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SLT.svg',
    websiteUrl: 'http://suilaunch.io',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x9aa4c03344444b53f4d9b1bca229ed2ac47504e3ea6cd0683ebdc0c5ecefd693::coin::T',
    faAddress: null,
    name: 'SWEAT',
    symbol: 'SWEAT',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whSWEAT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SWEAT.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'sweatcoin',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x394205c024d8e932832deef4cbfc7d3bb17ff2e9dc184fa9609405c2836b94aa::coin::T',
    faAddress: null,
    name: 'NEAR (Wormhole)',
    symbol: 'NEAR',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whNEAR',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/NEAR.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'near',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x1f9dca8eb42832b9ea07a804d745ef08833051e0c75c45b82665ef6f6e7fac32::coin::T',
    faAddress: null,
    name: 'Nexum Coin',
    symbol: 'NEXM',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whNEXM',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/NEXM.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'nexum',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x2305dd96edd8debb5a2049be54379c74e61b37ceb54a49bd7dee4726d2a6b689::coin::T',
    faAddress: null,
    name: 'SushiToken (Wormhole)',
    symbol: 'SUSHI',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whSUSHI',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/SUSHI.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'sushi',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xac0c3c35d50f6ef00e3b4db6998732fe9ed6331384925fe8ec95fcd7745a9112::coin::T',
    faAddress: null,
    name: 'Celo (Wormhole)',
    symbol: 'CELO',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whCELO',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/CELO.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'celo',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x419d16ebaeda8dc374b1178a61d24fb699799d55a3f475f427998769c537b51b::coin::T',
    faAddress: null,
    name: 'FTX Token',
    symbol: 'FTT',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whFTT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/FTT.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'ftx-token',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xcefd39b563951a9ec2670aa57086f9adb3493671368ea60ff99e0bc98f697bb5::coin::T',
    faAddress: null,
    name: 'Chain',
    symbol: 'XCN',
    decimals: 8,
    bridge: 'Wormhole',
    panoraSymbol: 'whXCN',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/XCN.webp',
    websiteUrl: null,
    category: 'Bridged',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: 'chain-2',
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x91b54cb4441c88fa21b7ca5b8b860e8b6fe726c23866bed91999823e65c1026d::GEMKRW::GEMKRW',
    faAddress: null,
    name: 'GEM.KRW',
    symbol: 'GEMKRW',
    decimals: 2,
    bridge: null,
    panoraSymbol: 'GEMKRW',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/GEMKRW.svg',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x7c2aaaaf3f019bbf7f02beed21fc4ec352cc38272f93cb11e61ec7c89bfe5f4b::xbtc::XBTC',
    faAddress: null,
    name: 'XBTC',
    symbol: 'XBTC',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'XBTC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/BTC.webp',
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::reserve::LP<0x1::aptos_coin::AptosCoin>',
    faAddress: null,
    name: 'Aries Aptos Coin LP Token',
    symbol: 'ar-APT',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ar-APT',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ar-APT.svg',
    websiteUrl: 'https://ariesmarkets.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::reserve::LP<0xdd89c0e695df0692205912fb69fc290418bed0dbe6e4573d744a6d5e6bab6c13::coin::T>',
    faAddress: null,
    name: 'Aries Solana (Wormhole) LP Token',
    symbol: 'ar-SOL',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'ar-SOL',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ar-SOL.svg',
    websiteUrl: 'https://ariesmarkets.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::reserve::LP<0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC>',
    faAddress: null,
    name: 'Aries USDC (Layerzero) LP Token',
    symbol: 'ar-zUSDC',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'ar-lzUSDC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ar-USDC.svg',
    websiteUrl: 'https://ariesmarkets.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress:
      '0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::reserve::LP<0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea::coin::T>',
    faAddress: null,
    name: 'Aries USDC (Wormhole) LP Token',
    symbol: 'ar-USDC',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'ar-whUSDC',
    logoUrl: 'https://raw.githubusercontent.com/PanoraExchange/Aptos-Tokens/main/logos/ar-USDC.svg',
    websiteUrl: 'https://ariesmarkets.xyz',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: false,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x397071c01929cc6672a17f130bd62b1bce224309029837ce4f18214cc83ce2a7::USDC::USDC',
    faAddress: null,
    name: '💸 USDC-APTOS.ORG',
    symbol: 'USDC-APTOS',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'USDC-APTOS',
    logoUrl: null,
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: true,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x48327a479bf5c5d2e36d5e9846362cff2d99e0e27ff92859fc247893fded3fbd::APTOS::APTOS',
    faAddress: null,
    name: '💸 aptclaim.net',
    symbol: '$APT',
    decimals: 6,
    bridge: null,
    panoraSymbol: '$APT',
    logoUrl: null,
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: true,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xbbc4a9af0e7fa8885bda5db08028e7b882f2c2bba1e0fedbad1d8316f73f8b2f::memes::Memecoins',
    faAddress: null,
    name: '⭐ aptosmeme.com',
    symbol: 'MEME',
    decimals: 8,
    bridge: null,
    panoraSymbol: 'MEME',
    logoUrl: null,
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: true,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xf658475dc67a4d48295dbcea6de1dc3c9af64c1c80d4161284df369be941dafb::moon_coin::MoonCoin',
    faAddress: null,
    name: 'ClaimAPTGift.com',
    symbol: 'aGift.site',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'aGift.site',
    logoUrl: null,
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: true,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0xbc106d0fef7e5ce159423a1a9312e011bca7fb57f961146a2f88003a779b25c2::QUEST::QUEST',
    faAddress: null,
    name: '▪ AptosQuest.io',
    symbol: 'COINS',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'COINS',
    logoUrl: null,
    websiteUrl: null,
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: true,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  },
  {
    chainId: 1,
    tokenAddress: '0x50788befc1107c0cc4473848a92e5c783c635866ce3c98de71d2eeb7d2a34f85::apt_rewards::APTRewards',
    faAddress: null,
    name: 'https://aptosx.app',
    symbol: 'APT Reward',
    decimals: 6,
    bridge: null,
    panoraSymbol: 'APT Reward',
    logoUrl: null,
    websiteUrl: 'https://aptosx.app',
    category: 'Native',
    isInPanoraTokenList: false,
    isBanned: true,
    panoraOrderIndex: 100000,
    coinGeckoId: null,
    coinMarketCapId: null
  }
]
