/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { TokenDistributorProcessor } from './types/eth/index.js'

TokenDistributorProcessor.bind({
  address: '0xB329e39Ebefd16f40d38f07643652cE17Ca5Bac1',
  network: 1,
}).onAllEvents((evt, ctx) => {
  ctx.meter.Counter('event_count').add(1, { name: evt.name })
  ctx.eventLogger.emit(evt.name, {
    ...evt.args.toObject(),
  })
})
